### ISSUE TITLE
bug_fixes

### ISSUE THREAD

**Issue by deepeerie** [eiire/100_matches#2]
Откорректировать ходы компьютера.

**Comment by eiire** [comment]
Сделал основную часть, но желательно вынести этот код в отдельную функцию. + Можно еще немного доработать ходы компьютера для случая, когда человек ходит вторым. 'VitekUn', при желании можешь взять эту задачу на себя.

**Comment by deepeerie** [comment]
Откорректировать выигрышную стратегию в случае, если человек ходит первым.  Исправить остальные недочеты в программе.
